import Head from 'next/head';

import LeftNav from '../components/LeftNav';
import Resume from '../components/Resume';

import { FlexHC } from '../styles/grid';

export default function Home() {
  return (
    <FlexHC>
      <Head>
        <title>Gerador de Documentos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftNav />
      <Resume />
   </FlexHC>
  )
}
