import Head from 'next/head'
import LeftNav from '../components/LeftNav'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gerador de Documentos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftNav />

   </div>
  )
}
